// 產生「自己的」工作副本與設定。只寫入 work/app、work/prepare-state.json 與
// work/專案指示.已填.txt；不部署、不連網、不執行其他程式，也不讀寫 .secrets/
// 或 work/private/，因此重跑不會覆蓋任何授權或驗收紀錄。
//
//   node tools/prepare.mjs                    產生／更新工作副本（每日寄信維持原狀，第一次一定關閉）
//   node tools/prepare.mjs --instructions-only 只產生已填好的專案指示（只需寄收件與日曆）
//   node tools/prepare.mjs --enable-daily      驗收通過後才可用：DAILY_ENABLED=true、crons=["0 1 * * *"]
//   node tools/prepare.mjs --disable-daily     關閉：DAILY_ENABLED=false、crons=[]
import {readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, readdirSync, copyFileSync} from 'node:fs';
import {join} from 'node:path';
import {KIT, WORK, APP, PRIVATE, STATE, TEMPLATE, DEFAULT_CONFIG, WRANGLER_CONFIG, parseArgs, fail} from './lib/paths.mjs';
import {readConfigFile, validateConfig, fingerprint} from './lib/config.mjs';
import {ownerSettings, wranglerSettings, DAILY_CRON} from './lib/prepared.mjs';

const MARKER = '.generated-by-prepare';
const ACCEPTANCE_MAX_AGE = 7 * 86400000;
let args;
try { args = parseArgs(process.argv.slice(2), {flags: ['--enable-daily', '--disable-daily', '--instructions-only'], options: ['--config']}); }
catch (error) { fail(error.message); }
const configPath = args.options['--config'] || DEFAULT_CONFIG;
const today = new Date(Date.now() + 8 * 3600000).toISOString().slice(0, 10);

let raw;
try { raw = readConfigFile(configPath); } catch (error) { fail(error.message); }

function writeInstructions(config) {
  let text = readFileSync(join(KIT, '專案指示.txt'), 'utf8');
  text = text.replace(/^把整份貼到.*$/m, '把整份貼到 ChatGPT「AI 秘書」專案的「指示」欄位。日曆與收件帳號已由 prepare.mjs 依 設定.json 填好。');
  text = text.replaceAll('{{個人日曆ID}}', config.calendar).replaceAll('{{收件主帳號}}', config.recipient);
  if (/\{\{[^}]*\}\}/.test(text)) fail('專案指示.txt 仍有未替換的欄位');
  mkdirSync(WORK, {recursive: true});
  writeFileSync(join(WORK, '專案指示.已填.txt'), text);
}

if (args.flags.has('--instructions-only')) {
  const {config, errors} = validateConfig(raw, 'instructions');
  if (errors.length) fail('設定.json 尚未完成：\n  - ' + errors.join('\n  - '));
  writeInstructions(config);
  console.log('✓ 已產生 work/專案指示.已填.txt（只用到寄收件與日曆欄位）。未部署、未連網。');
  process.exit(0);
}

const enable = args.flags.has('--enable-daily'), disable = args.flags.has('--disable-daily');
if (enable && disable) fail('--enable-daily 與 --disable-daily 不能同時使用');
const {config, errors} = validateConfig(raw, enable ? 'ready' : 'prepare');
if (errors.length) fail('設定.json 尚未完成，未產生任何檔案：\n  - ' + errors.join('\n  - '));

const fp = fingerprint(config);
const previous = existsSync(STATE) ? JSON.parse(readFileSync(STATE, 'utf8')) : null;
let daily = false;
if (enable) {
  const file = join(PRIVATE, 'acceptance.json');
  const acceptance = existsSync(file) ? JSON.parse(readFileSync(file, 'utf8')) : null;
  const problems = [];
  if (!acceptance) problems.push('找不到驗收紀錄：請先完成第 6 步（驗收信與讀回），再執行 node tools/admin.mjs ready-check --human-checks-passed');
  else {
    if (acceptance.ok !== true || acceptance.human_confirmed !== true) problems.push('驗收紀錄未通過（ready-check 有未完成項目）');
    if (acceptance.config_fingerprint !== fp) problems.push('驗收之後設定.json 有變更：請重新驗收');
    if (acceptance.schedule_enabled_at_check !== false) problems.push('驗收紀錄不是在排程關閉時產生');
    if (!(Date.now() - Date.parse(acceptance.checked_at) < ACCEPTANCE_MAX_AGE)) problems.push('驗收紀錄超過 7 天：請重新執行 ready-check');
  }
  if (problems.length) fail('不能開啟每日寄信：\n  - ' + problems.join('\n  - '));
  daily = true;
} else if (!disable && previous?.daily_enabled) {
  if (previous.daily_fingerprint === fp) daily = true;
  else console.warn('! 設定.json 的帳號／服務欄位已變更：每日寄信已自動改回「關閉」，需重新驗收後再用 --enable-daily 開啟。');
}

// work/app is fully generated. Only remove it when it carries our marker.
if (existsSync(APP)) {
  if (!existsSync(join(APP, MARKER)) && readdirSync(APP).length) fail('work/app 不是由 prepare 產生的資料夾，為避免刪錯檔案已停止。請手動檢查後移走它。');
  rmSync(APP, {recursive: true, force: true});
}
mkdirSync(APP, {recursive: true});
for (const file of readdirSync(TEMPLATE)) if (file !== 'owner-config.mjs') copyFileSync(join(TEMPLATE, file), join(APP, file));
const policyDate = previous?.policy_date || today;
writeFileSync(join(APP, 'owner-config.mjs'), '// Generated by tools/prepare.mjs from validated 設定.json. Do not edit; re-run prepare.\n' +
  `export const OWNER=Object.freeze(${JSON.stringify(ownerSettings(config, policyDate))});\n`);
writeFileSync(WRANGLER_CONFIG, '// Generated by tools/prepare.mjs. Edit 設定.json and re-run prepare instead of this file.\n' +
  JSON.stringify(wranglerSettings(config, daily), null, 2) + '\n');
writeFileSync(join(APP, MARKER), 'This folder is regenerated by tools/prepare.mjs. Manual edits are discarded.\n');
writeInstructions(config);
writeFileSync(STATE, JSON.stringify({format: 1, prepared_at: new Date().toISOString(), config_fingerprint: fp,
  daily_enabled: daily, daily_fingerprint: daily ? fp : null, policy_date: policyDate, origin_configured: !!config.origin}, null, 2) + '\n');

console.log(`✓ 工作副本已產生：work/app（未部署、未連網、未讀寫任何秘密）
  Worker：${config.worker_name}　Cloudflare 帳戶：${config.account_id}
  D1：${config.d1_database_name}（${config.d1_database_id}）
  寄件：${config.sender} → 收件：${config.recipient}　日曆：${config.calendar}（${config.timezone}）
  服務網址：${config.origin || '尚未填寫（首次部署後把網址填進 origin，再重跑 prepare 與 deploy）'}
  Google 專案：${config.google_project_id || '尚未填寫（第 3 步）'}
  每日寄信：${daily ? `開啟　DAILY_ENABLED=true　crons=["${DAILY_CRON}"]（UTC 01:00＝台灣 09:00）` : '關閉　DAILY_ENABLED=false　crons=[]'}
下一步請依操作手冊；部署需另外明確執行 node tools/deploy.mjs。`);
